apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nbc-bank-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/fransemalila/nbc-bank-gitops.git'
    targetRevision: HEAD
    path: templates
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true