apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops_database
  namespace: nbc
  labels:
    app: devops_database 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops_database 
  template:
    metadata:
      labels:
        app: devops_database 
      containers:
      - name: devops_database
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: "nbc_bank"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: root-password