apiVersion: apps/v1
kind: Deployment
metadata:
  name: nbc-app
  namespace: nbc
  labels:
    app: nbc-app
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nbc-app
  template:
    metadata:
      labels:
        app: nbc-app
        component: frontend
    spec:
      imagePullSecrets:
      - name: nbc-k8s
      volumes:
      - name: log-volume
        hostPath:
          path: /var/log/nbc_devops
          type: DirectoryOrCreate
      containers:
      - name: nbc-app
        image: fran123pv/nbc_devops_webservice:1.0.0
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/nbc_devops
        ports:
        - containerPort: 8765
          name: http
        env:
        - name: MYSQL_HOST
          value: "devops_database"
        - name: MYSQL_DB
          value: "nbc_bank"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: nbc-app-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8765
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8765
          initialDelaySeconds: 5
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /ready
            port: 8765
          failureThreshold: 30
          periodSeconds: 10