apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: nbc
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: nbc-bank-app-service
  namespace: nbc
spec:
  selector:
    app: nbc-bank-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8765